/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class FileSystem {
  static saveFile(fileData: Buffer, filePath: string): Promise<void>

  static getFile(filePath: string): Promise<Buffer>

  static deleteFile(filePath: string): Promise<void>

  static rename(oldPath: string, newPath: string): Promise<void>

  static createDir(dirPath: string): Promise<void>

  static removeDir(dirPath: string): Promise<void>
}
